station_data/urls.py
from django.urls import path

from . import views


app_name = 'station_data'
urlpatterns = [
    path('station/', views.station_view, name="station"),
]

track/urls.py
from django.urls import path

from . import views


app_name = 'track'
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('boarding-record/', views.Boarding_recordListView.as_view(), name="boarding_record"),
    path('boarding-record-create/', views.add_boarding_record, name="boarding_record_create"),
]

tt_track/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.urls import path, include

from .import settings_common, settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('track.urls')),
    path('stations/', include('station_data.urls')),

]

#開発サーバーでメディアを配信できるようにする設定
urlpatterns += static(settings_common.MEDIA_URL, document_root=settings.MEDIA_ROOT)

track/models.py
from django.db import models
from accounts.models import CustomUser

# Create your models here.

class Boarding_record(models.Model):
    """乗車記録モデル"""

    user = models.ForeignKey(CustomUser, on_delete=models.PROTECT)
    recording_start_date = models.DateField()
    recording_end_date = models.DateField(null=True, blank=True)
    distance = models.IntegerField(default=0)
    duration = models.TimeField(null=True, blank=True)
    title = models.CharField(max_length=30)
    height = models.IntegerField(default=0)
    comment = models.CharField(max_length=400, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.title


class Photo(models.Model):
    """写真モデル"""
    boarding_record = models.ForeignKey(Boarding_record, on_delete=models.CASCADE, null=True, default=None)
    photo = models.ImageField(default=None, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)


    """def __str__(self):
        return self.title"""


class Plotting(models.Model):
    """ルート作成モデル"""
    boarding_record = models.ForeignKey(Boarding_record, on_delete=models.CASCADE, null=True, default=None)
    latitude = models.FloatField(default=None, null=True, blank=True)
    longitude = models.FloatField(default=None, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)


   

track/forms.py
from django import forms
from .models import Boarding_record, Photo, Plotting

class Boarding_recordForm(forms.ModelForm):
    """乗車記録作成フォーム"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Boarding_record
        exclude = ('user',)

PhotoFormset = forms.inlineformset_factory(Boarding_record, Photo, fields='__all__', max_num=30, extra=1, can_delete=False)

PlottingFormset = forms.inlineformset_factory(Boarding_record, Plotting, fields='__all__', extra=1)

track/views.py
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Boarding_record
from django.urls import reverse_lazy
from .forms import Boarding_recordForm, PhotoFormset, PlottingFormset
from django.shortcuts import render, redirect


# Create your views here.
class IndexView(generic.TemplateView):
    template_name = 'index.html'

class Boarding_recordListView(LoginRequiredMixin, generic.ListView):
    model = Boarding_record
    template_name = 'boarding_record.html'

    def get_queryset(self):
        records = Boarding_record.objects.filter(user=self.request.user).order_by('-recording_start_date')
        return records

def add_boarding_record(request):
    form = Boarding_recordForm(request.POST or None)
    context = {'form': form}

    if request.method == 'POST' and form.is_valid():
        boarding_record = form.save(commit=False)
        boarding_record.user = request.user
        plotting_formset = PlottingFormset(request.POST, files=request.FILES, instance=boarding_record)
        photo_formset = PhotoFormset(request.POST, files=request.FILES, instance=boarding_record)

        if plotting_formset.is_valid() and photo_formset.is_valid(): 
            boarding_record.save()
            instances = plotting_formset.save(commit=False)
            for files in plotting_formset.deleted_objects:
                plotting_formset.delete()

            for files in instances:
                plotting_formset.save()
                
            photo_formset.save() 
            return redirect('track:boarding_record')

        # エラーメッセージつきのformsetをテンプレートへ渡すため、contextに格納
        else:
            context['plotting_formset'] = plotting_formset
            context['photo_formset'] = photo_formset 

    # GETのとき
    else:
        # 空のformsetをテンプレートへ渡す
        context['plotting_formset'] = PlottingFormset()
        context['photo_formset'] = PhotoFormset()

    return render(request, 'boarding_record_create.html', context)    


#def start_pref_station(request):

track/templates/base.html
{% load static %}

<html lang="ja">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}{% endblock %}</title>
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />

        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>

        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet" />

        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/one-page-wonder.css' %}" rel="stylesheet" />

        <!-- My style -->
        <link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}">
        {% block head %}{% endblock %}
    </head>

    <body>
        <div id="wrapper">
            <!-- Navigation-->
            <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
                <div class="container px-5">
                    <a class="navbar-brand" href="{% url 'track:index'%}">TRAIN TRIP TRACK</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse" id="navbarResponsive">
                        <ul class="navbar-nav me-auto">
                            {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link {% block active_boarding_record %}{% endblock %}" 
                                   href="{% url 'track:boarding_record' %}">BOARDING RECORD</a>
                            </li>
                            {% endif %}
                        </ul>

                        <ul class="navbar-nav ms-auto">
                            {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'account_logout' %}">Log Out</a>
                            </li>
                            {% else %}
                        
                            <li class="nav-item">
                                <a class="nav-link {% block active_signup %}{% endblock %}"
                                   href="{% url 'account_signup' %}">Sign Up</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link {% block active_login %}{% endblock %}" 
                                   href="{% url 'account_login' %}">Log In</a>
                            </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </nav>

            {% block header %}{% endblock %}
            {% block style %}{% endblock %}


            {% block contents %}{% endblock %}

            {% block script %}{% endblock %}


            <!-- Footer-->
            <footer class="py-5 bg-black">
                <div class="container px-5"><p class="m-0 text-center text-white small">Copyright &copy; TRAIN TRIP TRACK 2022</p></div>
            </footer>
            <!-- Bootstrap core JS-->
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
            <!-- Core theme JS-->
            <script src="js/scripts.js"></script>

            <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
            
            {% block extrajs %}{% endblock %}
        </div>
    </body>
</html>

track/templates/boarding_record.html
{% extends 'base.html' %}
{% load static %}

{% block title %}乗車記録一覧 | Train Trip Track{% endblock %}

{% block active_boarding_record %}active{% endblock %}

{% block head %}
<link href="{% static 'css/clean-blog.css' %}" rel="stylesheet">
{% endblock %}

{% block contents %}
<div class="container px-4 px-lg-5 my-div-style">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <div class="d-flex justify-content-end mb-4">
                <a class="btn btn-primary float-right" href="{% url 'track:boarding_record_create' %}">新規作成</a>
            </div>
            {% for item in object_list %}
            <div class="post-preview">
                <a href="#">
                    <h3 class="post-meta">
                        {{ item.recording_start_date }}
                    </h3>
                    <h2 class="title">
                        {{ item.title }}
                    </h2>
                </a>
            </div>
            <hr class="my-4">
            {% empty %}
            <p>乗車記録がありません。</p>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

track/templates/boarding_record_create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}乗車記録作成 | Train Trip Track{% endblock %}

{% block contents %}
<div class="container">
    <div class="my-div-style">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

            {{ form.non_field_errors }}

            {% for field in form %}
            <div class="mb-4 col-8">
                <label for="{{ field.id_for_label }}" class="form-label">
                    <strong>{{ field.label_tag }}</strong>
                </label>
                {{ field }}
                {{ field.errors }}
            </div>
            {% endfor %}

            <div id="map-drawing">
                <!-- <form action="" method="get"> -->
                <select id="start_pref" class="form-select" aria-label="Default select example">

                    <option selected>乗車開始した駅がある都道府県を選択してください</option>
                    <option value="1">1,北海道</option>
                    <option value="2">2,青森県</option>
                    <option value="3">3,岩手県</option>
                    <option value="4">4,宮城県</option>
                    <option value="5">5,秋田県</option>
                    <option value="6">6,山形県</option>
                    <option value="7">7,福島県</option>
                    <option value="8">8,茨城県</option>
                    <option value="9">9,栃木県</option>
                    <option value="10">10,群馬県</option>
                    <option value="11">11,埼玉県</option>
                    <option value="12">12,千葉県</option>
                    <option value="13">13,東京都</option>
                    <option value="14">14,神奈川県</option>
                    <option value="15">15,新潟県</option>
                    <option value="16">16,富山県</option>
                    <option value="17">17,石川県</option>
                    <option value="18">18,福井県</option>
                    <option value="19">19,山梨県</option>
                    <option value="20">20,長野県</option>
                    <option value="21">21,岐阜県</option>
                    <option value="22">22,静岡県</option>
                    <option value="23">23,愛知県</option>
                    <option value="24">24,三重県</option>
                    <option value="25">25,滋賀県</option>
                    <option value="26">26,京都府</option>
                    <option value="27">27,大阪府</option>
                    <option value="28">28,兵庫県</option>
                    <option value="29">29,奈良県</option>
                    <option value="30">30,和歌山県</option>
                    <option value="31">31,鳥取県</option>
                    <option value="32">32,島根県</option>
                    <option value="33">33,岡山県</option>
                    <option value="34">34,広島県</option>
                    <option value="35">35,山口県</option>
                    <option value="36">36,徳島県</option>
                    <option value="37">37,香川県</option>
                    <option value="38">38,愛媛県</option>
                    <option value="39">39,高知県</option>
                    <option value="40">40,福岡県</option>
                    <option value="41">41,佐賀県</option>
                    <option value="42">42,長崎県</option>
                    <option value="43">43,熊本県</option>
                    <option value="44">44,大分県</option>
                    <option value="45">45,宮崎県</option>
                    <option value="46">46,鹿児島県</option>
                    <option value="47">47,沖縄県</option>
                    <option value="99">99,その他</option>
                </select>

                <input type="submit" value="確定" onclick="clickBtn_startstation(event)" />
                <!-- </form> -->

                <script>
                    function clickBtn_startstation(event) {
                        event.preventDefault();
                        console.log('pref: ', document.getElementById("start_pref").value);
                        const start_pref_num = document.getElementById("start_pref").value;
                        // const url = '{% url "station_data:station" %}' + `?pref_cd=${start_pref_num}`;
                        const url = '{% url "station_data:station" %}' + `?add=名古屋&pref_cd=23`;
                        fetch(url)
                          .then((response) => response.json())
                          .then((data) => {
                            console.log(data);
                          });
                        // var map = L.map('map').setView(pref_center[start_pref_num], 15);
                    }
                </script>

            </div>

            <div class="container mt-3">

                <div id="map"></div>

            </div>

            <!-- Leaflet -->
            <script src="https://unpkg.com/leaflet@1.9.3/dist/leaflet.js"
                integrity="sha256-WBkoXOwTeyKclOHuWtc+i2uENFpDZ9YPdf5Hf+D7ewM=" crossorigin=""></script>
            <!-- Leaflet.Locate -->
            <script src="https://cdn.jsdelivr.net/npm/leaflet.locatecontrol@0.79.0/dist/L.Control.Locate.min.js"
                charset="utf-8"></script>
            <script>
                var map = L.map('map').setView([36, 137.59], 5);
                L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
                    maxZoom: 19,
                    attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
                }).addTo(map);

                let geojsonMarkerOptions = {
                    radius: 4,
                    fillColor: "#00ffff",
                    color: "#00f",
                    weight: 1,
                    opacity: 1,
                    fillOpacity: 0.8
                };

                L.control.locate().addTo(map);
                const urls = [
                    '#',
                ];
                urls.forEach((url) => {
                    fetch(url)
                        .then((response) => response.json())
                        .then((data) => {
                            L.geoJson(data, {
                                pointToLayer: function (feature, cordinate) {
                                    return L.circleMarker(cordinate, geojsonMarkerOptions)
                                },
                                onEachFeature: (feature, layer) => {
                                    layer.bindPopup(feature.properties.station_name);
                                }
                            }).addTo(map);
                        });
                });
            </script>

            <div class="mb-3">
                <label for="formFileMultiple" class="form-label">写真</label>
                {{ photo_formset.management_form }}
                <div id="photo-formset">
                    {% for photo in photo_formset %}
                    {{ photo.as_p }}
                    {% endfor %}
                </div>

                <p id="photo_set-empty" class="d-none">
                    <label for="id_photo_set-__prefix__-photo">Photo:</label>
                    <input type="file" name="photo_set-__prefix__-photo" accept="image/*"
                        id="id_photo_set-__prefix__-photo">
                    <input type="hidden" name="photo_set-__prefix__-boarding_record"
                        id="id_photo_set-__prefix__-boarding_record">
                    <input type="hidden" name="photo_set-__prefix__-id" id="id_photo_set-__prefix__-id">
                </p>

                <button id="add-photo" type="button" class="btn btn-secondary">写真の追加</button>
            </div>


            <div class="row"></div>
            {{ plotting_formset.management_form }}
            {% for plotting_form in plotting_formset %}
            <div id="plotting-area" class="col-sm-4">
                {{ plotting_form.as_p }}
            </div>
            <button id="add" type="button" class="btn btn-secondary">座標の追加</button>
            <button class="btn btn-primary" type="submit">保存</button>
        </form>
    </div>
    {% endfor %}
</div>
</div>
{% endblock %}

{% block extrajs %}
<script>
    $(function () {
        var totalCoordinateElement = $('input#id_plotting_set-TOTAL_FORMS');
        var currentCoordinateCount = parseInt(totalCoordinateElement.val());
        $('button#add').on('click', function () {
            const newLatitudeForm = document.createElement('p');
            let newLatitudeLabel = $('<label>', {
                for: 'id_plotting_set-' + currentCoordinateCount + '-latitude',
                text: 'Latitude:'
            });
            var latitudeElement = $('<input>', {
                type: 'number',
                name: 'plotting_set-' + currentCoordinateCount + '-latitude',
                id: 'id_plotting_set-' + currentCoordinateCount + '-latitude',
            });
            $('div#plotting-area').append(newLatitudeForm);
            $('div#plotting-area p:last-child').append(newLatitudeLabel, latitudeElement);
            const newLongitudeForm = document.createElement('p');
            let newLongitudeLabel = $('<label>', {
                for: 'id_plotting_set-' + currentCoordinateCount + '-longitude',
                text: 'Longitude:'
            });
            var longitudeElement = $('<input>', {
                type: 'number',
                name: 'plotting_set-' + currentCoordinateCount + '-longitude',
                id: 'id_plotting_set-' + currentCoordinateCount + '-longitude',
            });
            $('div#plotting-area').append(newLongitudeForm);
            $('div#plotting-area p:last-child').append(newLongitudeLabel, longitudeElement);
            const newDeleteCheck = document.createElement('p');
            let newDeleteLabel = $('<label>', {
                for: 'id_plotting_set-' + currentCoordinateCount + '-DELETE',
                text: '削除:'
            });
            let deleteElement_box = $('<input>', {
                type: 'checkbox',
                name: 'plotting_set-' + currentCoordinateCount + '-DELETE',
                id: 'id_plotting_set-' + currentCoordinateCount + '-DELETE',
            });
            let deleteElement_b_r = $('<input>', {
                type: 'hidden',
                name: 'plotting_set-' + currentCoordinateCount + '-boarding_record',
                id: 'id_plotting_set-' + currentCoordinateCount + '-boarding_record',
            });
            let deleteElement_id = $('<input>', {
                type: 'hidden',
                name: 'plotting_set-' + currentCoordinateCount + '-id',
                id: 'id_plotting_set-' + currentCoordinateCount + '-id',
            });
            $('div#plotting-area').append(newDeleteCheck);
            $('div#plotting-area p:last-child').append(newDeleteLabel, deleteElement_box, deleteElement_b_r, deleteElement_id);
            currentCoordinateCount += 1;
            totalCoordinateElement.attr('value', currentCoordinateCount);

        });
    });
</script>

<script>
    const addPhotoButton = document.getElementById('add-photo');
    const emptyForm = document.getElementById('photo_set-empty');
    const photoFormset = document.getElementById('photo-formset');
    const photoMax = parseInt(document.getElementById('id_photo_set-MAX_NUM_FORMS').value);

    addPhotoButton.addEventListener('click', () => {
        const form = emptyForm.cloneNode(true);
        const formSetCount = document.getElementById('id_photo_set-TOTAL_FORMS');
        const count = parseInt(formSetCount.value);

        form.removeAttribute('id');
        form.removeAttribute('class');
        const label = form.querySelector('label');
        label.setAttribute('for', label.getAttribute('for').replace('__prefix__', count));

        const input1 = form.querySelector('#id_photo_set-__prefix__-photo');
        input1.setAttribute('id', input1.getAttribute('id').replace('__prefix__', count));
        input1.setAttribute('name', input1.getAttribute('name').replace('__prefix__', count));

        const input2 = form.querySelector('#id_photo_set-__prefix__-boarding_record');
        input2.setAttribute('id', input2.getAttribute('id').replace('__prefix__', count));
        input2.setAttribute('name', input2.getAttribute('name').replace('__prefix__', count));

        const input3 = form.querySelector('#id_photo_set-__prefix__-id');
        input3.setAttribute('id', input3.getAttribute('id').replace('__prefix__', count));
        input3.setAttribute('name', input3.getAttribute('name').replace('__prefix__', count));

        photoFormset.appendChild(form);

        formSetCount.value = count + 1;

        if (formSetCount.value >= photoMax) {
            addPhotoButton.remove();
        }
    });
</script>

{% endblock %}

track/templates/boarding_record_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}乗車記録詳細 | Train Trip Track{% endblock %}

track/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Web上にあなたの鉄道の旅を記録できるサービス | Train Trip Track{% endblock %}

{% block header %}

<header class="masthead text-center text-white">
    <div class="masthead-content">
        <div class="container px-5">
            <h1 class="masthead-heading mb-0">Train Trip Track</h1>
            <h2 class="masthead-subheading mb-0">あなた専用の鉄道乗車記録保存サービス</h2>
            <a class="btn btn-primary btn-xl rounded-pill mt-5" href="#scroll">LOG IN</a>
        </div>
    </div>
    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div>
    <div class="bg-circle-4 bg-circle"></div>
</header>
{% endblock %}

{% block style %}
<!-- leaflet -->
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.3/dist/leaflet.css"
  integrity="sha256-kLaT2GOSpHechhsozzB+flnD+zUyjE2LlfWPgU04xyI=" crossorigin="" />

<!-- Leaflet.Locate -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/leaflet.locatecontrol@0.79.0/dist/L.Control.Locate.min.css" />
<style>
  #map {
    height: 700px;
  }
</style>
{% endblock %}

{% block contents %}

<div class="container mt-3">

    <div id="map"></div>
  
    
</div>

{% endblock %}

{% block script %}
<!-- Leaflet -->
<script src="https://unpkg.com/leaflet@1.9.3/dist/leaflet.js"
  integrity="sha256-WBkoXOwTeyKclOHuWtc+i2uENFpDZ9YPdf5Hf+D7ewM=" crossorigin=""></script>
<!-- Leaflet.Locate -->
<script src="https://cdn.jsdelivr.net/npm/leaflet.locatecontrol@0.79.0/dist/L.Control.Locate.min.js"
  charset="utf-8"></script>
<script>
  var map = L.map('map').setView([36, 137.59], 5);
  L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
    maxZoom: 19,
    attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
  }).addTo(map);

  let geojsonMarkerOptions = {
    radius: 4,
    fillColor: "#00ffff",
    color: "#00f",
    weight: 1,
    opacity: 1,
    fillOpacity: 0.8
  };
  
  L.control.locate().addTo(map);
  const urls = [
    '{% static "geojson/全国の駅_2.geojson" %}',
  ];
  urls.forEach((url) => {
    fetch(url)
      .then((response) => response.json())
      .then((data) => {
        L.geoJson(data, {
          pointToLayer: function (feature,cordinate) {
          return L.circleMarker(cordinate,geojsonMarkerOptions)},
          onEachFeature: (feature, layer) => {
            layer.bindPopup(feature.properties.station_name);
          }
        }).addTo(map);
      });
  });
</script>
{% endblock %}